# Generated by Django 3.0.11 on 2020-11-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='userId',
        ),
    ]
